### ISSUE TITLE
Revamp weapon handling

### ISSUE THREAD

**Issue by necrodoom** [kryps1/ComplexBossesFromHell#11]
Currently, there are several weapon classes, as well as zombies dropping weapons. The combination of these means that a user can easily grab a strong weapon, such as a quad or a DTR and make all the earlier levels easy. In addition, strong weapon drops form later boss levels can easily flip over a level's difficulty.

What i suggest is removing all external weapon drops from zombies, bosses, as well as the classes. Weapons should be given based on stage and not pure luck. Readjustment of boss HP may be needed due to firepower increasing.

Unlocks:
Start - fists, pistol, shotgun, chainsaw
map01 - super shotgun, assault rifle.
map06 - minigun.
map11 - rocket launcher, grenade launcher
map16 - quad shotgun
map21 - plasma rifle
map26 - demon tech rifle
map30 - BFG10k

Weapons that arent listed:
assault shotgun - mediocre DPS, uses ammo too quickly.
railgun - mediocre DPS
bfg9.5k - too powerful compared to bosses, as well as ease of use
dtbfg - too powerful, capable of removing most bosses in a minute.
mp40 - too similar to assault rifle and doesnt have any worthwhile usages.

**Comment by kryps1** [comment]
I will check with the guy behind Complex Doom to see if I'm allowed to change that mechanic.  Given the way BFH works (having progression w/ "upgrades"), I suspect there shouldn't be a problem with allowing me to do this.

**Comment by kryps1** [comment]
Fixed.
